### ISSUE TITLE
converter does not work

### ISSUE THREAD

**Issue by zsoltty91** [twhittock/avatto_me167#3]
Dear Twhittock!

I installed this converter but unfortunately Z2M does not recognise the device correctly.

I installed the script in the z2m folder and add to the configuration but i get this error again.

Zigbee2MQTT:warn  2022-10-21 19:21:48: Received message from unsupported device with Zigbee model 'TS0601' and manufacturer name '_TZE200_bvu2wnxz'

Folder: /config/zigbee2mqtt

config:
data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: "-d -d"
  log: true
  permit_join: true
  frontend: true
mqtt:
  server: mqtt://192.168.0.53:1883
  user: yourMQTT
  password: yourMQTTpass
serial:
  port: >-
    /dev/serial/by-id/usb-Silicon_Labs_slae.sh_cc2652rb_stick_-_slaesh_s_iot_stuff_00_12_4B_00_23_93_32_3B-if00-port0
advanced:
  log_level: debug
external_converters:
  - me167.js

Can you help me what can be the problem?

Thank you!

**Comment by twhittock** [comment]
I'd recommend you use the configuration settings inside the zigbee2mqtt UI, not the home assistant configuration, as per the instructions I put in the readme.

Other than that, it all sounds ok, but I'm hardly an expert on configuring z2m, so perhaps a forum or something may get you better help?

Good luck!

**Comment by twhittock** [comment]
I re-read the instructions in the readme, and saw they were too brief. I improved them, I hope that helps.

**Comment by Stooovie** [comment]
In the me167.js file there's a statement that "The model ID from: Device with modelID 'TS0601' is not supported", so we're probably out of luck. it doesn't work for me either.
