### ISSUE TITLE
Cannot change heating setpoint from HA

### ISSUE THREAD

**Issue by jpoittevin** [twhittock/avatto_me167#4]
Hello,

I'm not sure it's an issue with this converter but being new to HA and TRV, I'm struggling to find where the issue is in my setup. I managed to install HA and Z2M addon, this converter and I succesfully added my TRV in Z2M and HA. But when I change the setpoint, either from a card or directly from the Z2M frontend, I can see a log in Z2M with the desired value but a few seconds after, another line appears in the logs of Z2M resetting the value to and arbitrary value I don't know where it comes from.
I probably do something wrong and I would appreciate any clue you could give to help me find where my issue is.
Best regards,

Jérôme

**Comment by twhittock** [comment]
Hi - perhaps the TRV is in time programming mode (auto), instead of manual (heat) ?

**Comment by jpoittevin** [comment]
You're right. I think I had misunderstood this mode. Setting to manual makes the TRV work as I was expecting it to. Thanks for your answer and your work 👍 .
